backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

    
media_folder: static/img
public_folder: /img

collections:
  - name: "articles"
    label: "articles"
    folder: "src/content/articles"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "article"}
      - {label: "Features Post", name: "featuredpost", widget: "boolean", default: true}
      - {label: "Article", name: "article", widget: object, fields: [
        {label: "Title", name: "title", widget: string},
        {label: "Date", name: "date", widget: date},
        {label: "URL", name: "url", widget: string},
        {label: "Thumbnail", name: "thumbnail", widget: image}
      ]}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/index.md"
        label: "Landing Page"
        name: "landingPage"
        fields:
          - {label: "Template Key", name: templateKey, widget: "hidden", default: "landing-page"}
          - {label: "Title", name: title, widget: string, default: "Do something"}
      - file: "src/pages/about/index.md"    
        label: "About Page"
        name: "about"
        fields:
          - {label: "Template Key", name: templateKey, widget: "hidden", default: "landing-page"}
          - {label: "About Page", name: aboutPage, widget: object, fields: [
            {label: "Title", name: title, widget: string},
            {label: "Sections", name: "sections", widget: list, fields:[
              {label: "Title", name: "title", widget: string, required: true},
              {label: "Body", name: "body", widget: string, required: true},
            ]}
          ]}
      - file: "src/pages/contact/index.md"    
        label: "Contact Page"
        name: "contact"
        fields:
          - {label: "Template Key", name: templateKey, widget: "hidden", default: "landing-page"}
          - {label: "Contact Page", name: contactPage, widget: object, fields: [
            {label: "Title", name: title, widget: string},
            {label: "Contact Form", name: "contactForm", widget: object, fields: [
              {label: "Telephone", name: "telephone", widget: string, required: true},
              {label: "Email", name: "email", widget: string, required: true},
              {label: "Address", name: "address", widget: string, required: true},
              {label: "Subtitle", name: "subtitle", widget: string, required: true},
              {label: "links", name: "body", widget: object, fields: [
                {label: "Facebook", name: "facebook", widget: string, required: true},
                {label: "Twitter", name: "twitter", widget: string, required: true},
                {label: "LinkedIn", name: "linkedin", widget: string, required: true},
              ]},
            ]}
          ]}
      
      